name: Tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0']
        os: [ubuntu-latest, macos-latest]
        dependency-version: [lowest, highest]

    name: PHP ${{ matrix.php }} - prefer-${{ matrix.dependency-version }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite

      - uses: ramsey/composer-install@v1
        id: composer-run
        continue-on-error: true
        with:
          dependency-versions: ${{ matrix.dependency-version }}

      - name: Execute tests
        if: matrix.php != '8.0' || ( steps.composer-run.outcome == 'success' && steps.composer-run.conclusion == 'success' )
        run: vendor/bin/phpunit
